### ISSUE TITLE
Week1 tasks

### ISSUE THREAD

**Issue by Aryaman22102002** [Aryaman22102002/Wall-e-simulation-ros2#1]
- Tuesday- Install Ubuntu
- Wednesday- Find URDF for self balancing bot and start making the bot
- Thursday- Complete the bot
- Friday- Search for world file and create launch file
- Saturday- Start with algorithms for bot movement

**Comment by MOLOCH-dev** [comment]
Use this format to create a Task List for the Week : https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

**Comment by Aryaman22102002** [comment]
- [x] Install Ubuntu
- [x] Find URDF for self balancing bot and start making the bot
- [x] Complete the bot
- [x] Search for world file
- [x] create launch file
